-- 1) Crea la tabla STG (columnas pensadas para mapear tu Excel)
CREATE TABLE stg_atencion (
  -- Medidas / fecha de atención
  fecha_atencion                  DATE,
  duracion_minutos               NUMBER,

  -- Paciente
  dni_paciente                   CHAR(8),
  sexo_paciente                  CHAR(1),
  ubigeo_paciente                VARCHAR2(6),

  -- Profesional
  dni_profesional                CHAR(8),
  servicio_profesional           VARCHAR2(100),
  condicion_laboral_profesional  VARCHAR2(50),

  -- Diagnóstico
  codigo_cie10                   VARCHAR2(10),
  resultado_final                VARCHAR2(100),
  codigo_emergencia              VARCHAR2(20),

  -- Ubicación
  codigo_topico                  VARCHAR2(20),
  codigo_centro_atencion         VARCHAR2(50)
);


SELECT COUNT(*) FROM STG_ATENCION;

-- 1) Total de filas en staging
SELECT COUNT(*) AS TOTAL_FILAS
FROM STG_ATENCION;

-- 2) Rango de fechas de atención
SELECT 
    MIN(FECHA_ATENCION) AS FECHA_MIN,
    MAX(FECHA_ATENCION) AS FECHA_MAX
FROM STG_ATENCION;

-- 3) Nulos en campos clave (paciente/profesional/fecha)
SELECT
    COUNT(*) AS TOTAL_FILAS,
    SUM(CASE WHEN FECHA_ATENCION   IS NULL THEN 1 ELSE 0 END) AS NULOS_FECHA,
    SUM(CASE WHEN DNI_PACIENTE     IS NULL THEN 1 ELSE 0 END) AS NULOS_DNI_PACIENTE,
    SUM(CASE WHEN DNI_PROFESIONAL  IS NULL THEN 1 ELSE 0 END) AS NULOS_DNI_PROFESIONAL
FROM STG_ATENCION;



---------------------------------------------------------
-- DIMENSIONES DEL MODELO ESTRELLA
---------------------------------------------------------

-- 1) Dimensión TIEMPO
CREATE TABLE DIM_TIEMPO (
  ID_TIEMPO              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FECHA_COMPLETA         DATE       NOT NULL,
  ANIO                   NUMBER(4)  NOT NULL,
  MES                    NUMBER(2)  NOT NULL,
  NOMBRE_MES             VARCHAR2(20),
  SEMANA_EPIDEMIOLOGICA  NUMBER(2)
);

CREATE INDEX IX_DIM_TIEMPO_FECHA ON DIM_TIEMPO(FECHA_COMPLETA);

-- 2) Dimensión PACIENTE
CREATE TABLE DIM_PACIENTE (
  ID_PACIENTE   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DNI_PACIENTE  CHAR(8),
  NOMBRE_COMPLETO VARCHAR2(150),
  SEXO          VARCHAR2(10),
  UBIGEO        VARCHAR2(6)
);

-- 3) Dimensión PROFESIONAL
CREATE TABLE DIM_PROFESIONAL (
  ID_PROFESIONAL   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  DNI_PROFESIONAL  CHAR(8),
  SERVICIO         VARCHAR2(100),
  CONDICION_LABORAL VARCHAR2(50)
);

-- 4) Dimensión DIAGNOSTICO
CREATE TABLE DIM_DIAGNOSTICO (
  ID_DIAGNOSTICO   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CODIGO_CIE10     VARCHAR2(10),
  RESULTADO_FINAL  VARCHAR2(100),
  CODIGO_EMERGENCIA VARCHAR2(20)
);

-- 5) Dimensión UBICACION
CREATE TABLE DIM_UBICACION (
  ID_UBICACION          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CODIGO_TOPICO         VARCHAR2(20),
  CODIGO_CENTRO_ATENCION VARCHAR2(50)
);

---------------------------------------------------------
-- TABLA DE HECHOS
---------------------------------------------------------
CREATE TABLE HECHOS_ATENCIONES (
  PK_HECHO                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_TIEMPO                  NUMBER NOT NULL,
  ID_PACIENTE                NUMBER NOT NULL,
  ID_PROFESIONAL             NUMBER NOT NULL,
  ID_DIAGNOSTICO             NUMBER NOT NULL,
  ID_UBICACION               NUMBER NOT NULL,
  CONTADOR_ATENCIONES        NUMBER DEFAULT 1,
  DURACION_ATENCION_MINUTOS  NUMBER,

  CONSTRAINT FK_HECHO_TIEMPO
    FOREIGN KEY (ID_TIEMPO)     REFERENCES DIM_TIEMPO(ID_TIEMPO),
  CONSTRAINT FK_HECHO_PACIENTE
    FOREIGN KEY (ID_PACIENTE)   REFERENCES DIM_PACIENTE(ID_PACIENTE),
  CONSTRAINT FK_HECHO_PROFESIONAL
    FOREIGN KEY (ID_PROFESIONAL) REFERENCES DIM_PROFESIONAL(ID_PROFESIONAL),
  CONSTRAINT FK_HECHO_DIAGNOSTICO
    FOREIGN KEY (ID_DIAGNOSTICO) REFERENCES DIM_DIAGNOSTICO(ID_DIAGNOSTICO),
  CONSTRAINT FK_HECHO_UBICACION
    FOREIGN KEY (ID_UBICACION)   REFERENCES DIM_UBICACION(ID_UBICACION)
);




--------------------------------------------------
-- CARGA DE LA DIMENSIÓN TIEMPO
--------------------------------------------------
INSERT INTO DIM_TIEMPO (
  FECHA_COMPLETA,
  ANIO,
  MES,
  NOMBRE_MES,
  SEMANA_EPIDEMIOLOGICA
)
SELECT
  FECHA_ATENCION                                   AS FECHA_COMPLETA,
  EXTRACT(YEAR  FROM FECHA_ATENCION)              AS ANIO,
  EXTRACT(MONTH FROM FECHA_ATENCION)              AS MES,
  INITCAP(
    TO_CHAR(
      FECHA_ATENCION,
      'MONTH',
      'NLS_DATE_LANGUAGE=SPANISH'
    )
  )                                               AS NOMBRE_MES,
  TO_NUMBER(TO_CHAR(FECHA_ATENCION, 'WW'))        AS SEMANA_EPIDEMIOLOGICA
FROM STG_ATENCION
WHERE FECHA_ATENCION IS NOT NULL
GROUP BY FECHA_ATENCION;


-------------------
---Validamos
------------------
SELECT COUNT(*) AS TOTAL_FECHAS
FROM DIM_TIEMPO;

SELECT * 
FROM DIM_TIEMPO
FETCH FIRST 10 ROWS ONLY;




---------------------------------------------------------
-- CARGA DE LA DIMENSION PACIENTE
---------------------------------------------------------
INSERT INTO DIM_PACIENTE (
  DNI_PACIENTE,
  SEXO,
  UBIGEO
)
SELECT DISTINCT
  DNI_PACIENTE,
  CASE 
    WHEN SEXO_PACIENTE = 'M' THEN 'Masculino'
    WHEN SEXO_PACIENTE = 'F' THEN 'Femenino'
    ELSE 'No especificado'
  END AS SEXO,
  UBIGEO_PACIENTE AS UBIGEO
FROM STG_ATENCION
WHERE DNI_PACIENTE IS NOT NULL;


---------------------------------------------------------
-- VALIDACIÓN DIM_PACIENTE
---------------------------------------------------------
-- Total de pacientes en la dimensión
SELECT COUNT(*) AS TOTAL_PACIENTES
FROM DIM_PACIENTE;

-- Comparar con DNIs distintos del staging (por control)
SELECT COUNT(DISTINCT DNI_PACIENTE) AS DNIS_DISTINTOS_STG
FROM STG_ATENCION
WHERE DNI_PACIENTE IS NOT NULL;

-- Ver primeras filas
SELECT *
FROM DIM_PACIENTE
FETCH FIRST 10 ROWS ONLY;



---------------------------------------------------------
-- CARGA DE LA DIMENSIÓN PROFESIONAL
---------------------------------------------------------

INSERT INTO DIM_PROFESIONAL (
  DNI_PROFESIONAL,
  SERVICIO,
  CONDICION_LABORAL
)
SELECT DISTINCT
  DNI_PROFESIONAL,
  SERVICIO_PROFESIONAL,
  CONDICION_LABORAL_PROFESIONAL
FROM STG_ATENCION
WHERE DNI_PROFESIONAL IS NOT NULL;

---------------
--Total en la dimensión
---------------
SELECT COUNT(*) AS TOTAL_PROFESIONALES
FROM DIM_PROFESIONAL;


--------------
----Comparar con el staging
--------------

SELECT COUNT(DISTINCT DNI_PROFESIONAL) AS DNIS_DISTINTOS_STG
FROM STG_ATENCION
WHERE DNI_PROFESIONAL IS NOT NULL;

------------
---Ver primeras filas
-----------
SELECT *
FROM DIM_PROFESIONAL
FETCH FIRST 10 ROWS ONLY;


---------------------------------------------------------
-- CARGA DE LA DIMENSIÓN DIAGNOSTICO
---------------------------------------------------------

INSERT INTO DIM_DIAGNOSTICO (
  CODIGO_CIE10,
  RESULTADO_FINAL,
  CODIGO_EMERGENCIA
)
SELECT DISTINCT
  CODIGO_CIE10,
  RESULTADO_FINAL,
  CODIGO_EMERGENCIA
FROM STG_ATENCION
WHERE CODIGO_CIE10 IS NOT NULL;


---------------------------------------------------------
-- VALIDACIÓN DIM_DIAGNOSTICO
---------------------------------------------------------

-- 1) Total de registros en la dimensión
SELECT COUNT(*) AS TOTAL_DIAGNOSTICOS
FROM DIM_DIAGNOSTICO;

-- 2) Comparar con CIE10 distintos del staging
SELECT COUNT(DISTINCT CODIGO_CIE10) AS CIE10_DISTINTOS_STG
FROM STG_ATENCION
WHERE CODIGO_CIE10 IS NOT NULL;

-- 3) Ver algunas filas
SELECT *
FROM DIM_DIAGNOSTICO
FETCH FIRST 10 ROWS ONLY;


-------------------------------------------------------------
-- CARGA DE LA DIMENSIÓN UBICACION
-------------------------------------------------------------

INSERT INTO DIM_UBICACION (
    CODIGO_TOPICO,
    CODIGO_CENTRO_ATENCION
)
SELECT DISTINCT
    CODIGO_TOPICO,
    CODIGO_CENTRO_ATENCION
FROM STG_ATENCION
WHERE CODIGO_TOPICO IS NOT NULL
   OR CODIGO_CENTRO_ATENCION IS NOT NULL;

---------------------
--- validacion dimension ubicacion
---------------------
SELECT COUNT(*) AS TOTAL_UBICACIONES
FROM DIM_UBICACION;

SELECT *
FROM DIM_UBICACION
FETCH FIRST 10 ROWS ONLY;



-------------------------------------------------------------
-- CARGA DE LA TABLA DE HECHOS HECHOS_ATENCIONES
-------------------------------------------------------------

INSERT INTO HECHOS_ATENCIONES (
  ID_TIEMPO,
  ID_PACIENTE,
  ID_PROFESIONAL,
  ID_DIAGNOSTICO,
  ID_UBICACION,
  CONTADOR_ATENCIONES,
  DURACION_ATENCION_MINUTOS
)
SELECT
  dt.ID_TIEMPO,
  dp.ID_PACIENTE,
  dpr.ID_PROFESIONAL,
  dd.ID_DIAGNOSTICO,
  du.ID_UBICACION,
  1 AS CONTADOR_ATENCIONES,
  sa.DURACION_MINUTOS
FROM STG_ATENCION sa
JOIN DIM_TIEMPO dt
  ON dt.FECHA_COMPLETA = sa.FECHA_ATENCION
JOIN DIM_PACIENTE dp
  ON dp.DNI_PACIENTE = sa.DNI_PACIENTE
JOIN DIM_PROFESIONAL dpr
  ON dpr.DNI_PROFESIONAL = sa.DNI_PROFESIONAL
JOIN DIM_DIAGNOSTICO dd
  ON dd.CODIGO_CIE10 = sa.CODIGO_CIE10
JOIN DIM_UBICACION du
  ON du.CODIGO_TOPICO         = sa.CODIGO_TOPICO
 AND du.CODIGO_CENTRO_ATENCION = sa.CODIGO_CENTRO_ATENCION
WHERE sa.FECHA_ATENCION       IS NOT NULL
  AND sa.DNI_PACIENTE         IS NOT NULL
  AND sa.DNI_PROFESIONAL      IS NOT NULL
  AND sa.CODIGO_CIE10         IS NOT NULL;


-- Total de filas en la tabla de hechos
SELECT COUNT(*) AS TOTAL_HECHOS
FROM HECHOS_ATENCIONES;



-- 5.1 Validar claves foráneas no nulas
SELECT COUNT(*) AS FILAS_CON_NULL_FK
FROM HECHOS_ATENCIONES
WHERE ID_TIEMPO      IS NULL
   OR ID_PACIENTE    IS NULL
   OR ID_PROFESIONAL IS NULL
   OR ID_DIAGNOSTICO IS NULL
   OR ID_UBICACION   IS NULL;

----no se encontraron filas con claves foráneas nulas en la tabla de hechos---

---Comparar conteo de atenciones vs staging
-- 5.2 Total de atenciones válidas en staging
SELECT COUNT(*) AS ATENCIONES_VALIDAS_STG
FROM STG_ATENCION
WHERE FECHA_ATENCION   IS NOT NULL
  AND DNI_PACIENTE     IS NOT NULL
  AND DNI_PROFESIONAL  IS NOT NULL
  AND CODIGO_CIE10     IS NOT NULL;
  
  -- 5.3 Total de atenciones en la tabla de hechos
SELECT SUM(CONTADOR_ATENCIONES) AS ATENCIONES_EN_HECHOS
FROM HECHOS_ATENCIONES;

---“La tabla de hechos refleja X atenciones, mientras que la tabla staging registra Y atenciones válidas.
---La diferencia se debe al nivel de granularidad definido (por ejemplo, múltiples diagnósticos por atención, reglas de filtrado, etc.)”.



-- Suma de duración en staging (solo registros válidos)
SELECT SUM(DURACION_MINUTOS) AS SUMA_DURACION_STG
FROM STG_ATENCION
WHERE FECHA_ATENCION   IS NOT NULL
  AND DNI_PACIENTE     IS NOT NULL
  AND DNI_PROFESIONAL  IS NOT NULL
  AND CODIGO_CIE10     IS NOT NULL;
  
  -- Suma de duración en hechos
SELECT SUM(DURACION_ATENCION_MINUTOS) AS SUMA_DURACION_HECHOS
FROM HECHOS_ATENCIONES;



SELECT COUNT(*) AS DURACIONES_NO_NULAS
FROM STG_ATENCION
WHERE DURACION_MINUTOS IS NOT NULL;

SELECT DISTINCT DURACION_MINUTOS
FROM STG_ATENCION;

SELECT COUNT(*) AS DURACIONES_NO_NULAS_HECHOS
FROM HECHOS_ATENCIONES
WHERE DURACION_ATENCION_MINUTOS IS NOT NULL;


--La métrica de duración (DURACION_MINUTOS) no se encuentra presente en el dataset original del hospital (los valores están todos en NULL).
--Por lo tanto, la tabla de hechos HECHOS_ATENCIONES incluye la columna DURACION_ATENCION_MINUTOS, pero no puede ser utilizada como indicador porque no existen valores numéricos.
--El resto del modelo estrella funciona correctamente y permite análisis por fecha, paciente, profesional, diagnóstico y ubicación.


CREATE OR REPLACE VIEW VW_CUBO_ATENCIONES AS
SELECT
  h.PK_HECHO,
  -- Tiempo
  t.FECHA_COMPLETA,
  t.ANIO,
  t.MES,
  t.NOMBRE_MES,
  t.SEMANA_EPIDEMIOLOGICA,
  -- Paciente
  p.DNI_PACIENTE,
  p.SEXO,
  p.UBIGEO,
  -- Profesional
  pr.DNI_PROFESIONAL,
  pr.SERVICIO,
  pr.CONDICION_LABORAL,
  -- Diagnóstico
  d.CODIGO_CIE10,
  d.RESULTADO_FINAL,
  d.CODIGO_EMERGENCIA,
  -- Ubicación
  u.CODIGO_TOPICO,
  u.CODIGO_CENTRO_ATENCION,
  -- Medidas
  h.CONTADOR_ATENCIONES,
  h.DURACION_ATENCION_MINUTOS
FROM HECHOS_ATENCIONES h
JOIN DIM_TIEMPO      t  ON t.ID_TIEMPO      = h.ID_TIEMPO
JOIN DIM_PACIENTE    p  ON p.ID_PACIENTE    = h.ID_PACIENTE
JOIN DIM_PROFESIONAL pr ON pr.ID_PROFESIONAL = h.ID_PROFESIONAL
JOIN DIM_DIAGNOSTICO d  ON d.ID_DIAGNOSTICO = h.ID_DIAGNOSTICO
JOIN DIM_UBICACION   u  ON u.ID_UBICACION   = h.ID_UBICACION;


GRANT SELECT ON DMUS1.VW_CUBO_ATENCIONES TO US1;


