GRANT SELECT ON DMUS1.VW_CUBO_ATENCIONES TO US1;

GRANT SELECT ON DMUS1.DIM_PACIENTE       TO US1;
GRANT SELECT ON DMUS1.DIM_PROFESIONAL    TO US1;
GRANT SELECT ON DMUS1.DIM_UBICACION      TO US1;
GRANT SELECT ON DMUS1.DIM_DIAGNOSTICO    TO US1;
GRANT SELECT ON DMUS1.DIM_TIEMPO         TO US1;
GRANT SELECT ON DMUS1.HECHOS_ATENCIONES  TO US1;
GRANT SELECT ON DMUS1.VW_CUBO_ATENCIONES TO US1;

